buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        // REQUIRED for Kotlin Support
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // REQUIRED: Panels Repository
        maven {
            url = "https://mymaven.bylazar.com/releases"
        }
    }
}